# Generated by Django 5.1.6 on 2025-02-19 11:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['title'], 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='opportunitycategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Opportunity Categories'},
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
