# Generated by Django 5.1.6 on 2025-02-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('message', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('region', models.CharField(blank=True, choices=[('East Africa', 'East Africa'), ('North Africa', 'North Africa'), ('South Africa', 'South Africa'), ('West Africa', 'West Africa'), ('Central Africa', 'Central Africa')], max_length=50, null=True)),
                ('sector', models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Technology', 'Technology'), ('Health', 'Health'), ('Education', 'Education'), ('Finance', 'Finance'), ('Fashion', 'Fashion')], max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
