# Generated by Django 5.1.6 on 2025-02-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('abstract', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('document', models.FileField(upload_to='research_papers/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_papers', to='research.researchcategory')),
            ],
        ),
    ]
