# Generated by Django 5.1.6 on 2025-02-19 11:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name_plural': 'Research Papers'},
        ),
        migrations.AlterModelOptions(
            name='researchcategory',
            options={'verbose_name_plural': 'Research Categories'},
        ),
        migrations.AlterField(
            model_name='research',
            name='abstract',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
