# Generated by Django 5.1.6 on 2025-02-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_research_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='research_images/'),
        ),
        migrations.AlterField(
            model_name='research',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='research_papers/'),
        ),
    ]
