# Generated by Django 5.1.6 on 2025-04-14 09:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_research_image_alter_research_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='abstract',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
