# Generated by Django 5.1.6 on 2025-04-15 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_alter_research_abstract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['-publication_date'], 'verbose_name_plural': 'Research Papers'},
        ),
        migrations.AddField(
            model_name='research',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='research',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='research',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
