# Generated by Django 5.1.6 on 2025-02-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='partnergroup',
            options={'verbose_name_plural': 'Partner Groups'},
        ),
    ]
