# Generated by Django 5.1.6 on 2025-04-14 09:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_options_alter_partnergroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='partnergroup',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
