# Generated by Django 5.1.6 on 2025-02-19 11:47

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safeguard_policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safeguardpolicy',
            options={'verbose_name_plural': 'Safeguard Policies'},
        ),
        migrations.AddField(
            model_name='safeguardpolicy',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='safeguardpolicy',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
