# Generated by Django 5.1.6 on 2025-04-14 12:24

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastprogramme',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Summary of the past programme and what it covered in well-detailed.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='pastprogramme',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pastprogramme',
            name='title',
            field=models.CharField(help_text="Title of the past programme. E.g. 'MAF CHARITY OUTREACH'", max_length=100),
        ),
    ]
