# Generated by Django 5.1.6 on 2025-04-15 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_programmes', '0002_alter_pastprogramme_content_alter_pastprogramme_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastprogramme',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Past Programmes'},
        ),
        migrations.AddField(
            model_name='pastprogramme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pastprogramme',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pastprogramme',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
