# Generated by Django 5.1.6 on 2025-02-19 11:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impact',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
