# Generated by Django 5.1.6 on 2025-02-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0002_alter_impact_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impact',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Impact'},
        ),
    ]
