# Generated by Django 5.1.6 on 2025-04-14 09:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0004_category_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='State',
        ),
        migrations.AlterField(
            model_name='impact',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
