# Generated by Django 5.1.6 on 2025-02-19 11:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms_and_conditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name': 'Terms and Conditions', 'verbose_name_plural': 'Terms and Conditions'},
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
