# Generated by Django 5.1.6 on 2025-02-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Events'},
        ),
    ]
