# Generated by Django 5.1.6 on 2025-04-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
