# Generated by Django 5.1.6 on 2025-02-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bio', models.TextField()),
                ('expertise', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mentor_images/')),
            ],
        ),
    ]
