# Generated by Django 5.1.6 on 2025-02-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_alter_mentor_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name_plural': 'Mentors'},
        ),
    ]
