# Generated by Django 5.1.6 on 2025-04-14 09:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_mentor_designation_mentor_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Bio'),
        ),
    ]
