# Generated by Django 5.1.6 on 2025-04-14 09:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_approach', '0002_alter_ourapproach_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourapproach',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
