# Generated by Django 5.1.6 on 2025-02-27 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alter_alumni_options_alter_alumni_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['-graduation_year'], 'verbose_name_plural': 'Alumni'},
        ),
        migrations.AddField(
            model_name='alumni',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
