# Generated by Django 5.1.6 on 2025-04-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alter_alumni_options_alumni_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
