# Generated by Django 5.1.6 on 2025-02-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['-posted_date'], 'verbose_name_plural': 'Careers'},
        ),
    ]
