# Generated by Django 5.1.6 on 2025-04-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_career_description_alter_career_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
