# Generated by Django 5.1.6 on 2025-04-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_career_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='michaelanoka/career/'),
        ),
    ]
