# Generated by Django 5.1.6 on 2025-02-24 15:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_alter_media_options_alter_media_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cloudflare_link', models.URLField(help_text='Direct Cloudflare link to the audio file')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
