# Generated by Django 5.1.6 on 2025-04-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0005_alter_news_content_alter_pressrelease_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pressrelease',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
