# Generated by Django 5.1.6 on 2025-02-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_alter_aboutmentor_options_alter_aboutpartner_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMentor',
        ),
        migrations.DeleteModel(
            name='AboutPartner',
        ),
        migrations.DeleteModel(
            name='GetInvolved',
        ),
        migrations.DeleteModel(
            name='UpcomingEvent',
        ),
    ]
