# Generated by Django 5.1.6 on 2025-02-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_delete_aboutmentor_delete_aboutpartner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionVision',
        ),
    ]
