# Generated by Django 5.1.6 on 2025-02-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_delete_missionvision'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='youtube_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
