# Generated by Django 5.1.6 on 2025-02-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0007_missionandvision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateprofile',
            name='slug',
        ),
    ]
